version: '3.7'
services:


    jupyter:
      image: jupyter/pyspark-notebook:1386e2046833
      container_name: project_jupyter
      volumes:
          - ".:/home/jovyan/work"
      ports:
        - "8888:8888"
        - "4040-4050:4040-4050"
      depends_on:
        - mlflow


    mlflow:
        build:
            context: .
            dockerfile: Dockerfile_mlflow
        image: mlflow:0.0.1
        container_name: project_mlflow
        ports:
             - "5000:5000"
        entrypoint:
             - /opt/conda/bin/mlflow 
             - server
             - --host
             - "0.0.0.0"
             - --workers
             - "1"
             - --port
             - "5000"
             - --backend-store-uri 
             - file:///opt/mlruns